app/admin/views.py
import os

from pandas.io.sql import execute
from sqlalchemy import create_engine, String
import pyexcel_xls
import pyexcel_xlsx

import app
import pandas as pd
from config import Config, DevelopmentConfig
from app import excel
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    send_from_directory,
    current_app,
    jsonify,
    send_file)

from app.models import *
from app.decorators import admin_required
from flask_login import current_user, login_required
from app.admin.forms import *
from app.auth.forms import *
from flask_rq import get_queue
from app.email import send_email
from app.auth.email import send_confirm_email
from app.auth.email import send_password_reset_email
from app.auth.admin_decorators import check_confirmed
from sqlalchemy import func
from flask_ckeditor import upload_success, upload_fail

admin = Blueprint("admin", __name__)
photos = UploadSet("photos", IMAGES)

db_URI = DevelopmentConfig.SQLALCHEMY_DATABASE_URI
engine = create_engine(db_URI)


@admin.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@admin.route("/")
@login_required
@admin_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""
    all_applications = Application.query.filter_by(status='applied').order_by(Application.createdAt.desc()).all()
    published_listings = (
        Listing.query.filter_by(published=True)
            .order_by(Listing.createdAt.desc())
            .all()
    )
    all_listings = Listing.query.order_by(Listing.createdAt.desc()).all()
    latest_listings = Listing.query.order_by(Listing.createdAt.desc()).limit(4)
    croles = Role.query.filter_by(index="applicant").first_or_404()
    applicants = croles.users.order_by(User.createdAt.desc()).limit(5)
    publishers = Publisher.query.order_by(Publisher.createdAt.desc()).limit(5)
    interactionsCount = Application.query.count()
    applicationsCount = Application.query.filter_by(status="applied").count()
    listingsCount = Listing.query.filter_by(published=True).count()
    publishersCount = publishers.count()
    applicantsCount = applicants.count()
    # titles= [listing.title for listing in listings]

    # for listing in listings:
    #     count = Application.query.filter_by(job_listing_id=listing.id).count()
    #     list.append(count)
    return render_template(
        "admin/index.html",
        all_applications=all_applications,
        published_listings=published_listings,
        applicationsCount=applicationsCount,
        listingsCount=listingsCount,
        publishersCount=publishersCount,
        applicantsCount=applicantsCount,
        publishers=publishers,
        applicants=applicants,
        all_listings=all_listings,
        latest_listings=latest_listings,
        interactionsCount=interactionsCount
    )


@admin.route("/all_publishers")
@login_required
@admin_required
@check_confirmed
def publishers():
    """Publisher dashboard page."""
    publishers = Publisher.query.order_by(Publisher.createdAt.desc()).all()
    return render_template("admin/publishers.html", publishers=publishers)


@admin.route("/all_applicants")
@login_required
@admin_required
def applicants():
    """Admin dashboard page."""
    applicants = Applicant.query.order_by(Applicant.createdAt.desc()).all()
    return render_template("admin/applicants.html", applicants=applicants)


@admin.route("/all_applications")
@login_required
@admin_required
@check_confirmed
def applications():
    """Admin dashboard page."""
    applications = Application.query.filter_by(status="applied").order_by(Application.createdAt.desc()).all()
    family = Family
    education_documents = EducationDocuments
    education_details = Education
    p = Professional
    m = Membership
    employment = EmploymentHistory
    empL = EmploymentHistory.query.order_by(EmploymentHistory.createdAt.desc())
    return render_template("admin/applications.html", applications=applications,
                           # education_details=education_details,
                           # employment_details=employment_details,
                           # employment_history=employment_history,
                           # family=family,
                           # referees=referees,
                           p=p,
                           m=m,
                           family=family,
                           education_details=education_details,
                           education_documents=education_documents,
                           employment=employment,
                           empL=empL
                           )


@admin.route("/confirm_application/<id>/<status>")
@login_required
@admin_required
@check_confirmed
def confirm_application(id, status):
    application = Application.query.filter_by(id=id).first_or_404()
    if application.listing.publisher != current_user:
        return redirect(url_for("home.index"))
    application.status = status
    db.session.commit()
    flash("Status Updated", "green")
    return redirect(url_for("publisher.applications"))


@admin.route("/cancel_application", methods=["POST"])
@login_required
@admin_required
@check_confirmed
def cancel_application():
    id = request.args.get("id", 0, type=int)
    if request.method == "POST":
        application = Application.query.filter_by(id=id).first_or_404()
        if application.listing.publisher != current_user:
            return 401
        application.status = "cancelled"
        application.reason = request.form.get("reason")
        db.session.commit()
    applications = (
        Application.query.join(Listing, (Listing.id == Application.job_listing_id))
            .filter(Listing.publisher_id == current_user.id)
            .order_by(Application.createdAt.desc())
            .all()
    )
    return render_template("admin/_applications.html", applications=applications)


@admin.route("/all_listings")
@login_required
@admin_required
def job_listings():
    """All Listings Page."""
    # page = request.args.get("page", 1, type=int)
    listings = (
        Listing.query.order_by(Listing.createdAt.desc()).all()
    )

    return render_template("admin/listings.html", listings=listings)


@admin.route("/view_listing/<id>")
@login_required
@admin_required
@check_confirmed
def job_listing_id(id):
    """Single listing page."""
    listing = Listing.query.filter_by(id=id).first_or_404()
    job_applications = Application.query.filter_by(job_listing_id=listing.id).all()
    family = Family
    education_documents = EducationDocuments
    education_details = Education
    p = Professional
    m = Membership
    employment = EmploymentHistory
    return render_template("admin/view_listing.html",
                           listing=listing, job_applications=job_applications,
                           family=family, education_documents=education_documents,
                           education_details=education_details, p=p, m=m, employment=employment)


@admin.route("/listing_details")
@login_required
@admin_required
@check_confirmed
def job_listing_details():
    """All Listings Page."""
    id = request.args.get("since", 0, type=int)
    listing = Listing.query.filter_by(id=id).first_or_404()
    return render_template("admin/_listing_details.html", listing=listing)


@admin.route("/create_job_listing", methods=("GET", "POST"))
@login_required
@admin_required
@check_confirmed
def newListing():
    form = ListingForm()
    if form.validate_on_submit():
        new_job_listing = Listing(
            short_description=form.short_description.data,
            long_description=form.long_description.data,
            availability_from=form.availability_from.data,
            availability_to=form.availability_to.data,
            job_reference_number=form.job_reference_number.data,
            job_title=form.job_title.data,
            positions=form.positions.data,
            additional_info=form.additional_info.data,
            policy=form.policy.data,
            publisher=current_user,
            requires_license=form.requires_license.data
        )
        db.session.add(new_job_listing)
        db.session.commit()
        return redirect(url_for("admin.job_listings"))
    return render_template("admin/add_listing.html", form=form)


@admin.route("/edit_job_listing/<id>", methods=("GET", "POST"))
@login_required
@admin_required
@check_confirmed
def edit_listing(id):
    """Edit Job Listing page."""
    listing = Listing.query.filter_by(id=id).first_or_404()
    form = EditListingForm(obj=listing)

    if form.validate_on_submit():
        form.populate_obj(listing)
        db.session.commit()
        return redirect(url_for('admin.job_listings'))
    return render_template('admin/edit_listing.html', form=form, listing=listing)


@admin.route("/listings/delete/<id>")
@login_required
@admin_required
@check_confirmed
def delete_listing(id):
    listing = Listing.query.filter_by(id=id).first_or_404()
    db.session.delete(listing)
    db.session.commit()
    flash("Listing Deleted successfully", "success")
    return redirect(url_for("admin.job_listings"))


@admin.route("/view_publisher/<user_id>")
@login_required
@admin_required
@check_confirmed
def publisher_by(user_id):
    """Publisher dashboard page."""
    roles = Role.query.filter_by(index="publisher").first_or_404()
    publishers = roles.users
    return render_template("admin/manage_user.html", publishers=publishers)


@admin.route("/view_applicant/<id>")
@login_required
@admin_required
@check_confirmed
def view_applicant(id):
    """Admin dashboard page."""
    return render_template("admin/index.html")


@admin.route("/view_application/<id>")
@login_required
@admin_required
@check_confirmed
def view_application(id):
    """View application page."""
    application = Application.query.filter_by(id=id).first_or_404()
    user_id = application.user_id

app/templates/layouts/admin_base.html
{% import 'macros/admin_nav_macros.html' as sidebar %}
{% import 'macros/header_macros.html' as header %}
{% import 'macros/footer_macros.html' as footer %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %} {# Any templates that extend this
    template can set custom_head_tags to add scripts to their page #}
    {% block custom_head_tags %}

    {% endblock %}
</head>
<body>
<div class="main-wrapper">
    <!-- START NAV -->
    {% set dropdown = [
        ('All Users', [
            ('admin.registered_users', 'All Users', 'users'),
            ('admin.new_user', 'Add Users', 'user-plus'),
            ('admin.invite_user', 'Invite Users', 'user-plus'),
            ('admin.admin_settings', 'Settings', 'settings')
            ], '','users')
    ] %}
    {% block sidebar %}
        {{ sidebar.render_sidebar(current_user, dropdown) }}
    {% endblock %}

    <!-- END NAV -->
    <!-- START WRAPPER -->
    <div class="page-wrapper">
        {% block header %}
        {{ header.render_header(current_user) }}
        {% endblock %}
        <div class="page-content">

            {% include 'partials/_flashes.html' %}
            {# When extended, the content block contains all the html of the webpage #}

            {% block content %}
            {% endblock %}

        </div>
        {% block footer %}
        {{ footer.render_footer(current_user) }}
        {% endblock %}
    </div>
    <!-- END WRAPPER -->
</div>

{# Implement CSRF protection for site #} {% if csrf_token()|safe %}
<div style="visibility: hidden; display: none">
    <input
            type="hidden"
            name="csrf_token"
            value="{{ csrf_token()|safe }}"
    />
</div>
{% endif %}
{% block dash_scripts %}
<!--
  ================================================
  Scripts
  ================================================
-->
<!-- core:js -->
<script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
<!-- endinject -->
<!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/chartjs/Chart.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.resize.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/progressbar.js/progressbar.min.js') }}"></script>
<!-- end plugin js for this page -->
<!-- inject:js -->
<script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/template.js') }}"></script>
<!-- endinject -->

<script type="text/javascript"
        src="{{ url_for('static', filename='vendors/sweetalert/dist/sweetalert.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendors/dropify/js/dropify.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendors/moment/moment-with-locales.min.js') }}"></script>
{{ moment.include_moment() }} {{ moment.lang(g.locale) }}
{% endblock %}
<!-- custom js for this page -->
{% block scripts %}

{% endblock %}
<script type="text/javascript">
    $(document).ready(function () {
        $("#select-role").dropdown({
            onChange: function (value, text, $selectedItem) {
                $("td.user.role:contains(" + value + ")")
                    .closest("tr")
                    .removeClass("hidden")
                    .show();
                $("td.user.role")
                    .not(":contains(" + value + ")")
                    .closest("tr")
                    .addClass("hidden")
                    .hide();
            }
        });
    });

    function delete_item(id) {
        swal(
            {
                title: "Are you sure?",
                text: "You will not be able to recover this file!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            },
            function () {
                $(id).submit();
            }
        );
    }
</script>
</body>
</html>

app/templates/layouts/base.html
{% import 'macros/header_macros.html' as header with context %}
{% import 'macros/footer_macros.html' as footer %}
{% import 'macros/sidebar_macros.html' as sidebar %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %} {# Any templates that extend this
    template can set custom_head_tags to add scripts to their page #}
    {% block custom_head_tags %}

    {% endblock %}
</head>
<body>
    <div class="main-wrapper">
        <!-- START NAV -->
        {% block sidebar %}
            {{ sidebar.render_sidebar(current_user, dropdown) }}
        {% endblock %}
        <!-- END NAV -->

        <!-- START WRAPPER -->
        <div class="page-wrapper">
            {% block header %}
                {{ header.render_header(current_user) }}
            {% endblock %}
            <div class="page-content">
            {% include 'partials/_flashes.html' %}
            <!-- START CONTENT -->
            {# When extended, the content block contains all the html of the webpage #}

            {% block content %}
            {% endblock %}
            <!-- END CONTENT -->
            <!--
              ////////////////////////////////////////////////////////////////////////////
            -->
            </div>
            {% block footer %}
                {{ footer.render_footer(current_user) }}
            {% endblock %}
        </div>
        <!-- END WRAPPER -->
    </div>


    {# Implement CSRF protection for site #}
    {% if csrf_token()|safe %}
    <div style="visibility: hidden; display: none">
        <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}"/>
    </div>
    {% endif %}


{% block dash_scripts %}
    <!--
      ================================================
      Scripts
      ================================================
    -->
    <!-- core:js -->
    <script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{{ url_for('static', filename='vendors/chartjs/Chart.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.resize.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/progressbar.js/progressbar.min.js') }}"></script>
    <!-- end plugin js for this page -->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/template.js') }}"></script>
    <!-- endinject -->

    <script type="text/javascript" src="{{ url_for('static', filename='vendors/sweetalert/dist/sweetalert.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/dropify/js/dropify.min.js') }}"></script>
    {{ moment.include_moment() }} {{ moment.lang(g.locale) }}
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/moment/moment-with-locales.min.js') }}"></script>
{% endblock %}
    <!-- custom js for this page -->
{% block scripts %}

{% endblock %}
    <!-- end custom js for this page -->
    {% if current_user.is_authenticated %}

    {% endif %}
    <script>
        function delete_listing(id) {
            swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                },
                function () {
                    $(id).submit();
                });
        }

        var csrftoken = "{{ csrf_token() }}";

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });

        function cancelApplication(id) {
            swal({
                    title: "Cancel Application!",
                    text: "Are you sure you want To Cancel application?:",
                    type: "input", showCancelButton: true,
                    closeOnConfirm: false,
                    animation: "slide-from-top",
                    inputPlaceholder: "Reason for cancellation",
                    showLoaderOnConfirm: true,
                },
                function (inputValue) {
                    if (inputValue === false) return false;
                    if (inputValue === "") {
                        swal.showInputError("You need to write something!");
                        return false
                    }
                    data = {
                        reason: inputValue
                    }
                    $.post('{{ url_for('admin.cancel_application') }}?id=' + id, data
                ).
                    done(function (response) {
                        swal("Cancelled!", "Application successfully cancelled", "success");
                        $('#placehold').html(response);

                    }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        swal("Status: " + textStatus, "Error: " + errorThrown, "error");
                    });
                });
        }

        function get_profile(id) {
            $.get().done(function (response) {
                $('#profile-placehold').html(response);
            }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                swal("Status: " + textStatus, "Error: " + errorThrown, "error");
            });
        }


        function set_message_count(n) {
            $('#message_count').text(n);
            $('#message_count').css('visibility', n ? 'visible' : 'hidden');
        }

        $(document).ready(function() {
          url = "{{ url_for('applicant.check_family_details')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#family_details').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_personal_history')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#personal_history').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_contact_info')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#contact_info').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_education_info')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#education_info').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_employment_history')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#employment_history').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_employment_history_by_details')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#employment_history_by_details').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
        $(document).ready(function() {
          url = "{{ url_for('applicant.check_reference_details')  }}";
          $.get(url).done(function( response ) {
            if(response.status === true){
              $('#reference_details').removeClass("mdi-checkbox-blank-outline").addClass("mdi-checkbox-marked-outline");
            }
          })
        });
    </script>
</body>
</html>

app/templates/layouts/data_base.html
{% import 'macros/header_macros.html' as header with context %}
{% import 'macros/footer_macros.html' as footer %}
{% import 'macros/sidebar_macros.html' as sidebar %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %} {# Any templates that extend this
    template can set custom_head_tags to add scripts to their page #}
    {% block custom_head_tags %}

    {% endblock %}
</head>
<body>
    <div class="main-wrapper">
        <!-- START NAV -->
        {% block sidebar %}
            {{ sidebar.render_sidebar(current_user, dropdown) }}
        {% endblock %}
        <!-- END NAV -->

        <!-- START WRAPPER -->
        <div class="page-wrapper">
            {% block header %}
                {{ header.render_header(current_user) }}
            {% endblock %}
            <div class="page-content">
            {% include 'partials/_flashes.html' %}
            <!-- START CONTENT -->
            {# When extended, the content block contains all the html of the webpage #}

            {% block content %}
            {% endblock %}
            <!-- END CONTENT -->
            <!--
              ////////////////////////////////////////////////////////////////////////////
            -->
            </div>
            {% block footer %}
                {{ footer.render_footer(current_user) }}
            {% endblock %}
        </div>
        <!-- END WRAPPER -->
    </div>


    {# Implement CSRF protection for site #}
    {% if csrf_token()|safe %}
    <div style="visibility: hidden; display: none">
        <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}"/>
    </div>
    {% endif %}


{% block dash_scripts %}
    <!--
      ================================================
      Scripts
      ================================================
    -->
    <!-- core:js -->
    <script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{{ url_for('static', filename='vendors/chartjs/Chart.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.resize.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/progressbar.js/progressbar.min.js') }}"></script>
    <!-- end plugin js for this page -->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/template.js') }}"></script>
    <!-- endinject -->

    <script type="text/javascript" src="{{ url_for('static', filename='vendors/sweetalert/dist/sweetalert.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/dropify/js/dropify.min.js') }}"></script>
    {{ moment.include_moment() }} {{ moment.lang(g.locale) }}
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/moment/moment-with-locales.min.js') }}"></script>
{% endblock %}
    <!-- custom js for this page -->
{% block scripts %}

{% endblock %}
    <!-- end custom js for this page -->
    {% if current_user.is_authenticated %}

    {% endif %}
    <script>
        function delete_listing(id) {
            swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                },
                function () {
                    $(id).submit();
                });
        }

        var csrftoken = "{{ csrf_token() }}";

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });
    </script>
</body>
</html>

app/templates/layouts/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Careers' Portal - Kenyatta University Teaching, Referral & Research Hospital | Error</title>
    <!-- core:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='vendors/core/core.css') }}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- end plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/feather-font/css/iconfont.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendors/flag-icon-css/css/flag-icon.min.css') }}">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/style.css') }}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}"/>
</head>

<body>
    <div class="main-wrapper">
		<div class="page-wrapper full-page">
            {% block header %}
                <nav class="navbar" style="width: 100%; left: 0;">
                    <div class="navbar-content">
                        <ul class="navbar-nav">
                            <li class="nav-item ">
                                <a class="nav-link dropdown-toggle" href="https://kutrrh.go.ke/" id="languageDropdown" role="button"
                                   data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <span class="font-weight-medium ml-1 mr-1">Go Back To WebSite</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                {% endblock header %}
			<div class="page-content d-flex align-items-center justify-content-center">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
        <!-- core:js -->
        <script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
        <!-- endinject -->
        <!-- plugin js for this page -->
        <!-- end plugin js for this page -->
        <!-- inject:js -->
        <script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/template.js') }}"></script>

        {{ moment.include_moment() }} {{ moment.lang(g.locale) }}
        <!-- endinject -->
        <!-- custom js for this page -->
        {% block scripts %}
        {% endblock %}
        <!-- end custom js for this page -->
</body>
</html>