app/models/applicant.py
from .. import db
from datetime import datetime


class Applicant(db.Model):
    __tablename__ = 'applicants'
    id = db.Column(db.Integer, primary_key=True)
    overview = db.Column(db.String(2000))
    facebook = db.Column(db.String(120))
    twitter = db.Column(db.String(120))
    instagram = db.Column(db.String(120))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<Applicant\'%s\'>' % self.user_id

app/models/applications.py
from datetime import datetime

from .. import db
from flask_moment import Moment


class Application(db.Model):
    __tablename__ = 'applications'
    id = db.Column(db.Integer, primary_key=True)
    job_listing_id = db.Column(db.Integer, db.ForeignKey('job_listings.id'))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    complete_profile = db.Column(db.Boolean(), index=True, default=False)
    agreement = db.Column(db.Boolean(), index=True, default=False)
    status = db.Column(db.String(120), default='pending')
    education_documents = db.relationship('EducationDocuments', backref='applications', lazy='dynamic')
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<Application\'%s\'>' % self.job_listing_id

    def get_time(self):
        return self.createdAt

app/models/employment_history.py
from datetime import datetime

from .. import db


class EmploymentHistory(db.Model):
    __tablename__ = 'employment_history'
    id = db.Column(db.Integer, primary_key=True)
    name_of_institution = db.Column(db.String(64), index=True)
    year_from = db.Column(db.String(64), index=True)
    year_to = db.Column(db.String(64))
    duration = db.Column(db.String(64), index=True)
    job_group = db.Column(db.String(64), index=True)
    designation = db.Column(db.String(64))
    gross_salary = db.Column(db.String(64))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'), index=True)
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<EmploymentHistory \'%s\'>' % self.id


class Employment(db.Model):
    __tablename__ = 'employment'
    id = db.Column(db.Integer, primary_key=True)
    ministry = db.Column(db.String(64), index=True)
    station = db.Column(db.String(64), index=True)
    personal_employment_no = db.Column(db.String(64), index=True)
    present_substantive_post = db.Column(db.String(64), index=True)
    job_group = db.Column(db.String(64), index=True)
    date_of_current_appointment = db.Column(db.DateTime())
    effective_date = db.Column(db.DateTime())
    position_held = db.Column(db.String(64))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'), index=True)
    terms_of_service = db.Column(db.String(64), index=True)
    if_other = db.Column(db.String(200))
    gross_salary = db.Column(db.String(64))
    current_employer = db.Column(db.String(64))

    def __repr__(self):
        return '<Employment \'%s\'>' % self.id

app/models/notifications.py
from datetime import datetime
import json

from .. import db


class Notification(db.Model):
    __tablename__ = 'notifications'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    payload_json = db.Column(db.String(100), index=True)
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def get_data(self):
        return json.loads(str(self.payload_json))

app/applicant/__init__.py
from app.applicant.views import applicant

app/applicant/views.py
import uuid

from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory)
from flask_ckeditor import upload_success, upload_fail
from flask_login import current_user, login_required
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue
from flask_uploads import patch_request_class


from app.models.job_listings import *
from app.models.applications import *
from app.models.education_documents import *
from app.models.users import *
from app.applicant.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import User, Listing
from app.auth.email import send_password_reset_email
from app.auth.admin_decorators import check_confirmed
from app.decorators import checks_required
from werkzeug import secure_filename
from app.lib.upload_file import uploadfile
from app.auth.email import send_applicant_submitted
from werkzeug.datastructures import FileStorage, MultiDict
import africastalking



username = "kutrrh"
api_key = "316dda421e1e2ee09e95d218ee5b7cdddef60b2e4f3f129dd8f2537c64a271f2"
africastalking.initialize(username, api_key)

sms = africastalking.SMS

ALLOWED_EXTENSIONS = {
    "pdf"
}
MAX_CONTENT_LENGTH = 2 * 1024 * 1024
applicant = Blueprint("applicant", __name__)
certificates = UploadSet("certificates", ['pdf'])


@applicant.route("/")
@login_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""

    cancelled = current_user.applications.filter_by(status="cancelled").count()
    accepted = current_user.applications.filter_by(status="accepted").count()
    successful_applications = (
        current_user.applications.filter_by(status="applied").order_by(Application.createdAt.desc()).all()
    )
    all_applications = (
        current_user.applications.order_by(Application.createdAt.desc()).all()
    )
    all_jobs = Listing.query.filter_by(published=True).order_by(Listing.createdAt.desc()).all()

    return render_template(
        "applicant/index.html",
        cancelled=cancelled,
        accepted=accepted,
        all_applications=all_applications,
        successful_applications=successful_applications,
        all_jobs=all_jobs,
    )


@applicant.route("/new_application", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def new_application():
    """Start a new application."""
    form = SelectJob()
    job_title = form.job.data
    if form.validate_on_submit():
        return redirect(url_for("applicant.start_application", job_title=job_title.job_title))
    return render_template("applicant/select_job.html", form=form)


@applicant.route("/start_application/<job_title>", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def start_application(job_title):
    """Apply."""
    form = StartAppForm()
    job = Listing.query.filter_by(job_title=job_title).first_or_404()
    application = Application.query.join(User, (current_user.id == Application.user_id))\
        .filter(Application.job_listing_id == job.id).first()
    if form.validate_on_submit():
        if application:
            if application.status == 'applied':
                flash("You have applied for {} already boss!".format(job_title), "danger")
                return redirect(url_for("applicant.dashboard"))
        else:
            start_application = Application(
                job_listing_id=job.id,
                user_id=current_user.id
            )
            db.session.add(start_application)
            db.session.commit()
        return redirect(url_for("applicant.edit_application", id=job.id))
    return render_template("applicant/start_application.html", job=job, form=form)


@applicant.route("/apply_job/<id>", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def edit_application(id):
    user = current_user
    job_applied = Listing.query.filter_by(id=id).first()
    application_to_complete = Application.query.join(User, (current_user.id == Application.user_id))\
        .filter(Application.job_listing_id == id).first_or_404()
    this_ed = EducationDocuments.query.filter_by(user_id=user.id).first()
    form = ApplicationDocuments()
    if form.validate_on_submit():
        application_to_complete.agreement = form.terms_and_conditions.data
        application_to_complete.status = 'applied'
        docs = EducationDocuments(
            cv_url=str(user.id) + str(application_to_complete.id) + 'cv' + form.cv_url.data,
            cover_letter_url=str(user.id) + str(application_to_complete.id) + 'cl' + form.cover_letter_url.data,
            application_form_url=str(user.id) + str(application_to_complete.id) + 'ap' + form.application_form_url.data,
            user_id=current_user.id,
            application_id=application_to_complete.id,
            years_of_experience=form.years_of_experience.data,
            license=str(user.id) + str(application_to_complete.id) + 'l' + form.license.data
        )
        db.session.add(docs)
        db.session.commit()
        return redirect(url_for('applicant.submit_application', id=application_to_complete.id))
    return render_template("applicant/apply.html", job_applied=job_applied,
                           application_to_complete=application_to_complete, form=form)


@applicant.route("/start_edit_application/<id>", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def start_edit_application(id):
    """Apply."""
    form = EditStartAppForm()
    job = Listing.query.filter_by(id=id).first_or_404()
    application = Application.query.join(User, (current_user.id == Application.user_id))\
        .filter(Application.job_listing_id == job.id).first()
    if form.validate_on_submit():

        return redirect(url_for("applicant.edit_job_application", id=application.id))
    return render_template("applicant/start_edit_application.html", job=job, form=form)


@applicant.route("/edit_application/<id>", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def edit_job_application(id):
    """Edit Application page."""
    application_to_edit = Application.query.filter_by(id=id).first_or_404()
    this_ed = EducationDocuments.query.filter_by(user_id=current_user.id, application_id=id).first()
    job_id = application_to_edit.job_listing_id
    job_applied = Listing.query.filter_by(id=job_id).first()
    form = EditApplicationDocuments(obj=this_ed)
    if form.validate_on_submit():
        application_to_edit.status = 'applied'
        if this_ed:
            form.populate_obj(this_ed)
        else:
            new_docs = EducationDocuments(
                cv_url=str(current_user.id) + str(application_to_edit.id) + 'cv' + form.cv_url.data,
                cover_letter_url=str(current_user.id) + str(application_to_edit.id) + 'cl' + form.cover_letter_url.data,
                application_form_url=str(current_user.id) + str(application_to_edit.id) + 'ap' + form.application_form_url.data,
                user_id=current_user.id,
                application_id=application_to_edit.id,
                years_of_experience=form.years_of_experience.data,
                license=str(current_user.id) + str(application_to_edit.id) + 'l' + form.license.data
            )
            db.session.add(new_docs)
        db.session.commit()
        flash("Successfully updated.", "success")
        return redirect(url_for('applicant.submit_application', id=application_to_edit.id))
    return render_template("applicant/edit_job_app.html",
                           application_to_edit=application_to_edit, form=form, this_ed=this_ed,
                           job_applied=job_applied)


@applicant.route("/submit_final/<id>", methods=["post", "get"])
@login_required
@check_confirmed
@checks_required
def submit_application(id):
    this_ed = EducationDocuments.query.filter_by(user_id=current_user.id).first()
    this_applicant = Applicant.query.filter_by(user_id=current_user.id).first()
    user = User.query.filter_by(id=current_user.id).first_or_404()
    final_application = Application.query.filter_by(id=id).first()
    final_application.complete_profile = True
    final_application.status = "applied"
    if this_applicant is None:
        applicant = Applicant(
            user_id=current_user.id
        )
        db.session.add(applicant)
        db.session.commit()
    send_applicant_submitted(user)
    flash("Successfully applied for this vacancy.", "success")
    return redirect(url_for("applicant.view_applications"))
    # user = current_user

    # sms_message = "Dear {}, your job applicat>kutrrhion has been received successfully".format(current_user.full_name())
    # phone_number = "{}".format(current_user.phone_number_personal)
    # sender = "KUTRRH"
    #
    # print(sms_message)
    # print(phone_number)
    #
    # try:
    #     # That's it, hit send and we'll take care of the rest.
    #     response = sms.send(sms_message, [phone_number], sender)
    #     print(response)
    # except Exception as e:
    #     print('Encountered an error while sending: %s' % str(e))


@applicant.route("/personal_history", methods=["post", "get"])
@login_required
@check_confirmed
def personal_history():
    """Personal History page."""
    form = PersonalDetailsForm(obj=current_user)
    if form.validate_on_submit():
        form.populate_obj(current_user)
        db.session.commit()
        flash("Personal Details updated successfully", "success")
        return redirect(url_for("applicant.dashboard"))
    return render_template("applicant/personal_details.html", form=form)


@applicant.route("/check_personal_history")
@login_required
@check_confirmed
def check_personal_history():
    if current_user.first_name is not None and current_user.surname is not None and \
            current_user.second_name is not None and current_user.gender is not None and \

app/templates/applicant/applications.html
{% extends 'layouts/base.html' %}
 {% block custom_head_tags %}
 {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 col-xl-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-baseline mb-2">
                    <h6 class="card-title mb-0">My Applications</h6>
                    <p class="card-title">click on an application to edit</p>
                    <div class="dropdown mb-2">
                        <button class="btn p-0" type="button" id="dropdownMenuButton7" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton7">
                            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="eye"
                                                                                           class="icon-sm mr-2"></i>
                                <span class="">View</span></a>
                            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="edit-2"
                                                                                           class="icon-sm mr-2"></i>
                                <span class="">Edit</span></a>
                            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="trash"
                                                                                           class="icon-sm mr-2"></i>
                                <span class="">Delete</span></a>
                            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="printer"
                                                                                           class="icon-sm mr-2"></i>
                                <span class="">Print</span></a>
                            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="download"
                                                                                           class="icon-sm mr-2"></i>
                                <span class="">Download</span></a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                        <tr>
                            <th class="pt-0">#</th>
                            <th class="pt-0">Job Reference ID</th>
                            <th class="pt-0">Job Name</th>
                            <th class="pt-0">Application Deadline</th>
                            <th class="pt-0">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for application in my_applications %}
                        <tr>
                            <td>{{loop.index}}</td>
                            <td><a href="{%if application.status == 'pending'%}{{ url_for('applicant.start_edit_application', id=application.listing.id)}}{% else %}#{%endif%}">{{application.listing.job_reference_number}}</a>
                            </td>
                            <td><a href="{{ url_for('applicant.start_edit_application', id=application.listing.id)}}">{{application.listing.job_title}}</a>
                            </td>
                            <td>{{ "{:%d/%m/%Y}".format(application.listing.availability_to) }}</td>
                            <td>
                                {%if application.status == 'pending'%}<span class="badge badge-primary">Incomplete (Upload Documents)</span>
                                {%elif application.status == 'applied'%}<span class="badge badge-info-muted">Submitted</span>
                                {%elif application.status == 'accepted'%}<span class="badge badge-success">Accepted</span>
                                {%elif application.status == 'cancelled'%}<span class="badge badge-danger">Cancelled</span>{%endif%}
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                         <td>No Applications made</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div> <!-- row -->

{% endblock%}

app/templates/applicant/personal_details.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">STEP ONE</a></li>
        <li class="breadcrumb-item active" aria-current="page">Personal Details</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <form class="cmxform" method="post" action="{{url_for('applicant.personal_history')}}">
            {{form.hidden_tag()}}
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Personal Details</h4>
                            <p class="card-description">
                                Please fill in the following required fields.
                            </p>
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>Title</label>
                                        {{form.title(placeholder="Title", class="form-control")}}
                                        {%for error in form.title.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>First Name *</label>
                                        {{form.first_name(placeholder="First Name", class="form-control")}}
                                        {%for error in form.first_name.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>Second Name *</label>
                                        {{form.second_name(placeholder="Second Name", class="form-control")}}
                                        {%for error in form.second_name.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>Surname *</label>
                                        {{form.surname(placeholder="Surname", class="form-control")}}
                                        {%for error in form.surname.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Gender *</label>
                                        {{form.gender(placeholder="--Select--", class="form-control")}}
                                        {%for error in form.gender.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Home County *</label>
                                        {{form.home_county(placeholder="Home County", class="form-control")}}
                                        {%for error in form.home_county.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Year of Birth (yyyy)*</label>
                                        {{form.dob(placeholder="1999", class="form-control")}}
                                        {%for error in form.dob.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Civil Status *</label>
                                        {{form.civil_status(placeholder="Civil Status", class="form-control")}}
                                        {%for error in form.civil_status.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Nationality *</label>
                                        {{form.nationality(placeholder="Nationality", class="form-control")}}
                                        {%for error in form.nationality.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Ethnicity*</label>
                                        {{form.ethnicity(placeholder="Ethnicity", class="form-control")}}
                                        {%for error in form.ethnicity.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-check">
											<label class="form-check-label">
                                                {{form.disability(class="form-check-input", type="checkbox", style="")}}
												Do you have a disability *
											</label>
										</div>

                                        {%for error in form.disability.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>If YES, Nature of disability </label>
                                        {{form.disability_nature(placeholder="Nature of disability", class="form-control")}}
                                        {%for error in form.disability_nature.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>If YES, Disability Registration Details </label>
                                        {{form.disability_registration_details(placeholder="Disability registration details", class="form-control")}}
                                        {%for error in form.disability_registration_details.errors%}
                                        <span class="text-danger">{{error}}</span>
                                        {%endfor%}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    {{form.submit(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}
{% block scripts%}
    <script>
            $(function() {
      'use strict';

      if($('#datePicker').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });

        $('#datePicker').datepicker('setDate', '');
      }
    });
    </script>
{%  endblock %}

app/templates/applicant/start_edit_application.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<style>
    .col-sm-6, .desc{
        color: #76838f;;
    }
</style>
<!-- PAGE CSS-->
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xl-12 main-content pl-xl-4 pr-xl-5">
        <h4 class="page-title">Please Update Details for your application of {{job.job_title}}</h4>
        <hr class="mt-4 mb-4">

        <div class="row mb-lg-4">
            <div class="col-sm-6">
                <span style="color: #007bff;">Reference Number:</span> {{ job.job_reference_number }}
            </div>
            <div class="col-sm-6">
                <span style="color: #007bff;">Publication Date:</span> {{ "{:%d/%m/%Y}".format(job.availability_from) }}
            </div>
        </div>
        <div class="row mb-lg-4">
            <div class="col-sm-6">
                <span style="color: #007bff;">Job Title:</span> {{ job.job_title }}
            </div>
            <div class="col-sm-6">
                <span style="color: #007bff;">Deadline:</span> <span style="color: #ff3366">{{ "{:%d/%m/%Y}".format(job.availability_to) }}</span>
            </div>
        </div>
        <div class="row mb-lg-4">
            <div class="col-sm-6">
                <span style="color: #007bff;">Type of Contract:</span> {%if job.type_of_contract%}{{ job.type_of_contract }}
                {%else%} To be determined {%endif%}
            </div>
            <div class="col-sm-6">
               <span style="color: #007bff;"> Available Positions:</span> {{ job.positions }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                 <form class="cmxform" action="{{ url_for('applicant.start_edit_application', id=job.id)}}" method="post">
                        {{ form.hidden_tag() }}
                     {{ form.submit(class="btn btn-primary mt-lg-4", style="float: right;") }}
                 </form>
            </div>
        </div>

    </div>
</div>
{% endblock%}